### PR TITLE
Create api endpoints

### PR DESCRIPTION
**Pull request by KaskMIL**
# In this new Pull Request I'm adding the following features:
- Install JWT for user authorization.
- Add authentication for endpoints
- Create an endpoint to show all users.
- Create an endpoint to show all the posts for a user.
- Create an endpoint to list all the comments for a user's post.
- Create an endpoint to create a new comment.

## Endpoints
- Show all users: http://localhost:3000/api/v1/users/

- Show posts of a user: http://localhost:3000/api/v1/users/:user_id/posts

- Show all comments for a given post: http://localhost:3000/api/v1/users/:user_id/posts/:post_id/comments

- Show a comment for a given post: http://localhost:3000/api/v1/users/:user_id/posts/:post_id/comments

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Tom, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should be worked on by a team of two instead of one. Kindly ensure that your project is evenly contributed by all assigned group members of this project, and then request for another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
Hi Tom, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should be worked on by a team of two instead of one. Kindly ensure that your project is evenly contributed by all assigned group members of this project, and then request for another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @KaskMIL 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KaskMIL** [comment]
Hi @emmanuellekamwa
Thanks for your review!
Have a great day

**Pull request merged**
